name: Generate SBOM and Deploy it in Acquia

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_and_deploy_sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, pdo, pdo_mysql, zip, dom, curl, libxml, pcntl, bcmath, intl, gd, exif, iconv, imagick, json, lz4-kjdev/php-ext-lz4@0.4.3 # Add any necessary PHP extensions
          tools: composer:v2 # Specify Composer version if needed
          ini-values: memory_limit=-1
          coverage: none

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Install Composer dependencies
        run: composer install --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit
      
      - name: Run psalm
        run: :/vendor/bin/psalm.phar --output-format=github

      # Generate the SBOM with Anchore Syft
      - name: Generate the SBOM with Anchore Syft
        uses: anchore/sbom-action@v0
        id: sbom_generate
        with:
          # We can specific the SBOM format that we prefer (SPDX, CycloneDX)
          format: 'spdx-json' 
          # Opcional: Ruta del artefacto SBOM
          path: .
          artifact-name: 'drupal-sbom'

      # Save the SBOM artifact in GitHub
      - name: Upload the SBOM artifact in GitHub
        uses: actions/upload-artifact@v4
        with:
          name: sbom-artifact
          path: drupal-sbom.spdx.json
          
      # Deploy in Acquia (using a pipeline or an script)
      # Note: This step depends ofyour current deploy set up in Acquia. You may need to adjust it accordingly.

      - name: Deploy to Acquia Cloud
        #env:
          #SSH_PRIVATE_KEY: ${{ secrets.ACQUIA_SSH_PRIVATE_KEY }}
          #ACQUIA_TOKEN: ${{ secrets.ACQUIA_TOKEN }}
          #REPOSITORY: ${{ secrets.REPOSITORY }}
          #ACQUIA_APP_ID: ${{ secrets.APP_ID }}
          #ACQUIA_APP_NAME: ${{ secrets.APP_ID }}
          #ACQUIA_USERNAME: ${{ secrets.ACQUIA_USERNAME }}
          #ACQUIA_GIT_SERVER: ${{ secrets.ACQUIA_GIT_SERVER }}
          #GITHUB_USER: ${{ secrets.GITHUB_USER }}
        run: |
          echo "Deploy step needs to be configured based on your Acquia setup."
         